# Production environment configuration

app:
  debug: false
  
database:
  host: "${DB_HOST}"
  port: "${DB_PORT:5432}"
  name: "${DB_NAME}"
  ssl_enabled: true
  connection_timeout: 10
  
cache:
  provider: "redis"
  host: "${REDIS_HOST}"
  port: "${REDIS_PORT:6379}"
  
logging:
  level: "WARNING"
  
security:
  jwt_expiry: 1800  # 30 minutes for production
  
# Production optimizations
performance:
  enable_compression: true
  static_file_caching: true
  database_connection_pooling: true