apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-api
  namespace: fullstack-monolith-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: django-api
          env:
            - name: DEBUG
              value: "True"
            - name: LOG_LEVEL
              value: "DEBUG"
            - name: ALLOWED_HOSTS
              value: "*"
            - name: CORS_ALLOW_ALL_ORIGINS
              value: "True"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 60
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-celery-worker
  namespace: fullstack-monolith-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: celery-worker
          command:
            - celery
            - -A
            - config
            - worker
            - --loglevel=debug
            - --concurrency=2
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"