apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: fullstack-monolith-dev
spec:
  template:
    spec:
      containers:
        - name: redis
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: fullstack-monolith-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage