apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-web
  namespace: fullstack-monolith-prod
spec:
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/api/metrics"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - nextjs-web
                topologyKey: kubernetes.io/hostname
      containers:
        - name: nextjs-web
          env:
            - name: NODE_ENV
              value: "production"
            - name: NEXT_PUBLIC_API_URL
              value: "https://api.yourdomain.com/api/v1"
            - name: NEXT_PUBLIC_WS_URL
              value: "wss://api.yourdomain.com/ws"
            - name: NEXTAUTH_URL
              value: "https://yourdomain.com"
          resources:
            requests:
              memory: "512Mi"
              cpu: "400m"
            limits:
              memory: "1Gi"
              cpu: "800m"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
              scheme: HTTPS
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
              scheme: HTTPS
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3