apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: fullstack-monolith-prod
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - database
      containers:
        - name: postgres
          env:
            - name: POSTGRES_DB
              value: "fullstack_monolith_prod"
            - name: POSTGRES_INITDB_ARGS
              value: "--encoding=UTF-8 --locale=en_US.UTF-8"
            - name: POSTGRES_SHARED_PRELOAD_LIBRARIES
              value: "pg_stat_statements"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
                - -d
                - fullstack_monolith_prod
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
                - -d
                - fullstack_monolith_prod
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: fullstack-monolith-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: fast-ssd