# Generated by Django 4.2.23 on 2025-08-19 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('blog_post_published', 'Blog Post Published'), ('comment_added', 'Comment Added'), ('user_mentioned', 'User Mentioned'), ('newsletter_sent', 'Newsletter Sent'), ('system_alert', 'System Alert')], max_length=50, unique=True)),
                ('title_template', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('sound', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_dismiss_seconds', models.PositiveIntegerField(default=0, help_text='0 = no auto dismiss')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'db_table': 'core_notification_template',
            },
        ),
        migrations.CreateModel(
            name='WebSocketConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=255)),
                ('consumer_class', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error')], max_length=20)),
                ('close_code', models.IntegerField(blank=True, null=True)),
                ('connection_time', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WebSocket Connection',
                'verbose_name_plural': 'WebSocket Connections',
                'db_table': 'core_websocket_connection',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='core_websoc_user_id_39c4cf_idx'), models.Index(fields=['action', 'timestamp'], name='core_websoc_action_ed4d12_idx'), models.Index(fields=['consumer_class'], name='core_websoc_consume_d821f2_idx')],
            },
        ),
    ]
