apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-web
  namespace: fullstack-monolith
  labels:
    app: nextjs-web
    tier: frontend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: nextjs-web
  template:
    metadata:
      labels:
        app: nextjs-web
        tier: frontend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/api/metrics"
    spec:
      containers:
        - name: nextjs-web
          image: nextjs-web:latest
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: nextjs-secret
                  key: NEXTAUTH_SECRET
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: nextjs-secret
                  key: GOOGLE_CLIENT_ID
                  optional: true
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: nextjs-secret
                  key: GOOGLE_CLIENT_SECRET
                  optional: true
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: nextjs-secret
                  key: GITHUB_CLIENT_ID
                  optional: true
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: nextjs-secret
                  key: GITHUB_CLIENT_SECRET
                  optional: true
            - name: NEXT_PUBLIC_SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: nextjs-secret
                  key: NEXT_PUBLIC_SENTRY_DSN
                  optional: true
          envFrom:
            - configMapRef:
                name: nextjs-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-web-service
  namespace: fullstack-monolith
  labels:
    app: nextjs-web
    tier: frontend
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: nextjs-web