version: "3.8"

services:
  redis-node-1:
    image: redis:7-alpine
    container_name: redis-cluster-node-1
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7001:7000"
      - "17001:17000"
    volumes:
      - ./redis-cluster.conf:/usr/local/etc/redis/redis.conf
      - redis-cluster-data-1:/data/cluster
      - redis-cluster-logs-1:/var/log/redis
    environment:
      - REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1
      - REDIS_CLUSTER_ANNOUNCE_PORT=7001
    networks:
      - redis-cluster-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "7000", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis-node-2:
    image: redis:7-alpine
    container_name: redis-cluster-node-2
    command: redis-server /usr/local/etc/redis/redis.conf --port 7000 --cluster-announce-port 7002
    ports:
      - "7002:7000"
      - "17002:17000"
    volumes:
      - ./redis-cluster.conf:/usr/local/etc/redis/redis.conf
      - redis-cluster-data-2:/data/cluster
      - redis-cluster-logs-2:/var/log/redis
    environment:
      - REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1
      - REDIS_CLUSTER_ANNOUNCE_PORT=7002
    networks:
      - redis-cluster-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "7000", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis-node-3:
    image: redis:7-alpine
    container_name: redis-cluster-node-3
    command: redis-server /usr/local/etc/redis/redis.conf --port 7000 --cluster-announce-port 7003
    ports:
      - "7003:7000"
      - "17003:17000"
    volumes:
      - ./redis-cluster.conf:/usr/local/etc/redis/redis.conf
      - redis-cluster-data-3:/data/cluster
      - redis-cluster-logs-3:/var/log/redis
    environment:
      - REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1
      - REDIS_CLUSTER_ANNOUNCE_PORT=7003
    networks:
      - redis-cluster-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "7000", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis-node-4:
    image: redis:7-alpine
    container_name: redis-cluster-node-4
    command: redis-server /usr/local/etc/redis/redis.conf --port 7000 --cluster-announce-port 7004
    ports:
      - "7004:7000"
      - "17004:17000"
    volumes:
      - ./redis-cluster.conf:/usr/local/etc/redis/redis.conf
      - redis-cluster-data-4:/data/cluster
      - redis-cluster-logs-4:/var/log/redis
    environment:
      - REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1
      - REDIS_CLUSTER_ANNOUNCE_PORT=7004
    networks:
      - redis-cluster-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "7000", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis-node-5:
    image: redis:7-alpine
    container_name: redis-cluster-node-5
    command: redis-server /usr/local/etc/redis/redis.conf --port 7000 --cluster-announce-port 7005
    ports:
      - "7005:7000"
      - "17005:17000"
    volumes:
      - ./redis-cluster.conf:/usr/local/etc/redis/redis.conf
      - redis-cluster-data-5:/data/cluster
      - redis-cluster-logs-5:/var/log/redis
    environment:
      - REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1
      - REDIS_CLUSTER_ANNOUNCE_PORT=7005
    networks:
      - redis-cluster-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "7000", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis-node-6:
    image: redis:7-alpine
    container_name: redis-cluster-node-6
    command: redis-server /usr/local/etc/redis/redis.conf --port 7000 --cluster-announce-port 7006
    ports:
      - "7006:7000"
      - "17006:17000"
    volumes:
      - ./redis-cluster.conf:/usr/local/etc/redis/redis.conf
      - redis-cluster-data-6:/data/cluster
      - redis-cluster-logs-6:/var/log/redis
    environment:
      - REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1
      - REDIS_CLUSTER_ANNOUNCE_PORT=7006
    networks:
      - redis-cluster-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "7000", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis-cluster-init:
    image: redis:7-alpine
    container_name: redis-cluster-init
    command: >
      sh -c "
        sleep 10 &&
        redis-cli --cluster create 
        redis-node-1:7000 
        redis-node-2:7000 
        redis-node-3:7000 
        redis-node-4:7000 
        redis-node-5:7000 
        redis-node-6:7000 
        --cluster-replicas 1 
        --cluster-yes
      "
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    networks:
      - redis-cluster-network

volumes:
  redis-cluster-data-1:
  redis-cluster-data-2:
  redis-cluster-data-3:
  redis-cluster-data-4:
  redis-cluster-data-5:
  redis-cluster-data-6:
  redis-cluster-logs-1:
  redis-cluster-logs-2:
  redis-cluster-logs-3:
  redis-cluster-logs-4:
  redis-cluster-logs-5:
  redis-cluster-logs-6:

networks:
  redis-cluster-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
