apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-api
  namespace: fullstack-monolith-staging
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: django-api
          env:
            - name: DEBUG
              value: "False"
            - name: LOG_LEVEL
              value: "INFO"
            - name: ALLOWED_HOSTS
              value: "staging.yourdomain.com,staging-api.yourdomain.com"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-celery-worker
  namespace: fullstack-monolith-staging
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: celery-worker
          command:
            - celery
            - -A
            - config
            - worker
            - --loglevel=info
            - --concurrency=4
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "512Mi"
              cpu: "300m"