apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-web
  namespace: fullstack-monolith-staging
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: nextjs-web
          env:
            - name: NODE_ENV
              value: "production"
            - name: NEXT_PUBLIC_API_URL
              value: "https://staging-api.yourdomain.com/api/v1"
            - name: NEXT_PUBLIC_WS_URL
              value: "wss://staging-api.yourdomain.com/ws"
            - name: NEXTAUTH_URL
              value: "https://staging.yourdomain.com"
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "512Mi"
              cpu: "300m"