apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: fullstack-monolith-staging
spec:
  template:
    spec:
      containers:
        - name: redis
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: fullstack-monolith-staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard